
name: Issues
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  List-Issues:
    name: Listing Issues
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rewrite Readme
        uses: seed-of-apricot/issue-list-readme@v1.1.0
        with:
          GITHUB_TOKEN: '${{ secrets.TOKEN }}'
          pattern: '<!-- issueTable -->'
          labels: 'good first issue'
          state: 'open'

